Add Ex4
adifeiner/CodeU2017 pull request #7
Opened 2017-06-26 21:22 UTC by adifeiner

2017-06-27 09:58 UTC, brzozan requested changes
Very good!

I had only cosmetic comments.

2017-06-27 09:58 UTC, brzozan commented on Ex4.java
> +    private static void findAllTilesOfIsland(boolean[][] mapTiles, boolean[][] visit, int numOfRows, int numOfCols,
Minor naming nitpick: slightly more clear name could be something like `markAllTilesOfIsland`.

2017-06-27 09:58 UTC, brzozan commented on Ex4.java
> +     * The function check if the arguments legal and check
Typically you do not need to write that method checks arguments. Just explain its main functionality, i.e. finding all tiles that belong to the island containing tile `(rowIndex, colIndex)` and marking them as visited.

2017-06-27 09:58 UTC, brzozan commented on Ex4Test.java
> +        boolean[][] mapTiles = new boolean[4][4];
You could also initialize array via literal shaped in a nice rectangle, which would make it more clear what the map looks like:

```
boolean[][] mapTiles = {
    { false, true,  false, false },
    { true,  true,  false, false },
...
};
```

But feel free to leave it as is.

2017-06-27 09:58 UTC, brzozan commented on Ex4.java
> +     * @param numOfRow
Please add comments to all parameters and return value.

Also minor stylistic comment: it's good to add empty line between main description of the method and the block of `@param` lines.

2017-06-27 09:58 UTC, brzozan commented on Ex4Test.java
> +        Ex4 countIslands = new Ex4();
All the methods are static, so no need to create instance of Ex4. Same in other tests.

2017-07-01 14:48 UTC, adifeiner commented
Updating with the fix code, thanks!

2017-07-03 12:04 UTC, brzozan approved these changes
LGTM. Thank you!

2017-07-10 23:02 UTC, merged